language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

before_script:
  - travis_retry composer update --no-interaction --prefer-source

# script:
#   - if [ $(phpenv version-name) == "7.4" ]; then phpunit --coverage-text --coverage-clover=coverage.clover; else phpunit --no-coverage; fi

branches:
  except:
    - develop
