language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

before_script:
  - travis_retry composer update --no-interaction --prefer-source

script: phpunit --coverage-text --coverage-clover=coverage.clover

branches:
  only:
    - release/2.0.0
